import './style.css';import versionText from '../../version.txt?raw';
import {MultiplayerClient} from '@rmc/multiplayer-client';import {createRenderer} from './renderer.js';import {WEAPONS,sprite} from './art.js';import {makeInput,normalized} from './input.js';
const $=s=>document.querySelector(s),repo='https://github.com/SamuelAsherRivello/babylon-lite-enter-the-gungeon-clone',version=versionText.trim().replace('version=','');
$('#content_layer').remove();
$('#ui_layer').innerHTML=`
<header class="masthead"><a class="brand corner_top_left" href="${import.meta.env.BASE_URL}"><span class="brand-icon">✦</span><span>ENTER THE GUNGEON CLONE<small>BRASS & BRIMSTONE</small></span></a><div class="header-right corner_top_right"><span class="edition">AN ORIGINAL COOPERATIVE DUNGEON</span><a href="${repo}" target="_blank" rel="noopener">View source ↗</a></div></header>
<main class="layout">
<aside class="sidebar"><div class="eyebrow">ONE VAULT. ONE TEAM.</div><h1>Make every<br>shot count.</h1><p class="intro">Dodge the storm.<br>Bring your friends back.</p>
<section class="party-panel"><div class="section-head"><h2>Your crew</h2><span id="occupancy">0 / 4</span></div><div id="party"><p class="empty-party">Create a room to start.<br>Solo adventurers welcome.</p></div><button id="invite" class="subtle wide" disabled>Copy invite link <span>↗</span></button><p id="invite-note" class="tiny">Hot join. Hot drop. Always together.</p></section>
<section class="briefing"><h2>THE RUN</h2><ol><li><b>01</b><span>Hold the room<small>Clear the wave. Collect the loot.</small></span></li><li><b>02</b><span>Build your arsenal<small>Choose upgrades between waves.</small></span></li><li><b>03</b><span>Face the Warden<small>A boss waits every fifth wave.</small></span></li></ol></section>
<div class="revive-note"><span>✚</span><p>Stand near a downed ally<br>for 2 seconds to revive.</p></div><div class="controls"><p><kbd>W A S D</kbd><span>Move</span></p><p><kbd>MOUSE</kbd><span>Aim & shoot</span></p><p><kbd>SPACE</kbd><span>Dodge roll</span></p></div></aside>
<section class="game-column"><div class="stage-heading"><div><span class="eyebrow">THE COPPER KEEP</span><h2>A little courage. A lot of bullets.</h2></div><span class="coop-badge">1–4 PLAYERS <b>ONLINE CO-OP</b></span></div>
<div class="game-top"><span><i class="live-dot"></i><b id="connection">READY TO CONNECT</b></span><button id="room-code" class="code-button" disabled>PRIVATE ROOM</button></div>
<div class="wave-bar"><span>WAVE <b id="wave">—</b></span><span>ENEMIES <b id="enemies">—</b></span><span class="bullet-key"><i class="friendly-dot"></i> YOUR SHOTS <i class="enemy-dot"></i> ENEMY SHOTS</span></div>
<div id="content_layer" class="viewport"><canvas id="game" tabindex="0" aria-label="Cooperative dungeon arena. WASD to move, mouse aim, left click shoot, Space dodge."></canvas>
<div id="overlay" class="overlay"><div class="overlay-card"><span class="overlay-mark">✦</span><div class="eyebrow" id="overlay-kicker">THE VAULT IS WAITING</div><h2 id="overlay-title">Better together.</h2><p id="overlay-text">Create a private room, or follow your crew inside.</p>
<div id="admission"><button id="create" class="primary wide">Create room <span>→</span></button><div class="join-row"><input id="join-code" maxlength="4" placeholder="4-CHARACTER ROOM CODE" aria-label="Room code" autocomplete="off"><button id="join">Join ↗</button></div><small>Enter a code to join or create that private room. Leave it blank to get a generated code. Play solo or invite up to 3 friends.</small></div>
<button id="ready" class="primary wide" hidden>Ready up →</button><button id="retry" class="primary wide" hidden>Try again</button><button id="restart" class="primary wide" hidden>Restart team →</button><button id="new-room" class="subtle wide" hidden>Create a new room</button></div></div>
<div id="downed" class="downed" hidden>YOU ARE DOWN · An ally can revive you</div>
<div id="touch-controls"><div id="move-stick" class="stick" aria-label="Movement joystick"><i></i><span>MOVE</span></div><button id="touch-roll" aria-label="Dodge roll">↻<small>ROLL</small></button><div id="aim-stick" class="stick" aria-label="Aim and shoot joystick"><i></i><span>AIM + FIRE</span></div></div>
</div><div class="health-row"><span id="identity">YOUR EXPLORER</span><div class="health-track"><div id="health-fill"></div></div><b id="health">— / 100</b><div class="dodge-status"><span id="dodge-label">ROLL READY</span><div class="dodge-track"><i id="dodge-fill"></i></div></div></div>
<div class="weapon-label"><span>CHOOSE YOUR STARTING WEAPON</span><span>THREE WAYS TO MAKE AN ENTRANCE</span></div><div class="weapon-grid">${WEAPONS.map((w,i)=>`<button class="weapon-card" data-weapon="${w.id}" aria-pressed="${i===0}"><span class="weapon-icon">${w.icon}</span><div><small>${w.tag}</small><strong>${w.name}</strong><p>${w.desc}</p></div><kbd>${i+1}</kbd></button>`).join('')}</div>
<section id="upgrades" hidden><div class="upgrade-title"><span>VAULT SECURED · SHARED REWARD</span><b id="break-timer"></b></div><div class="upgrade-grid">${[['damage','Hot loads','+20% damage'],['haste','Quick hands','Faster firing'],['vitality','Second wind','Health & healing'],['agility','Light feet','Move faster']].map(([id,name,desc])=>`<button data-upgrade="${id}"><strong>${name}</strong><small>${desc}</small></button>`).join('')}</div><p id="upgrade-note"></p></section>
<div class="field-note"><span>✧</span><p>No friendly fire. Loot belongs to the crew. A run ends when everyone is down.</p><button id="leave" class="subtle" disabled>Leave room ↗</button></div></section></main>
<footer><div class="settings corner_bottom_left"><button id="pause">Ⅱ Pause</button><button id="sound" aria-pressed="false">Sound off</button><button id="fullscreen">⛶ Fullscreen</button></div><span id="event" role="status">An original dungeon. A shared adventure.</span><span class="corner_bottom_right">WEBGPU <i>·</i> <b id="version">v${version}</b></span></footer>`;
const session=new MultiplayerClient(import.meta.env.VITE_MULTIPLAYER_URL||import.meta.env.VITE_SERVER_URL||'https://rmc-colyseus-multiplayer-server.vercel.app','gungeon');
let renderer,gpuError='',paused=false,sound=false,audio,previousPhase='',previousShots=0,dead=false,raf,disposed=false;
const keys=new Set();let move={x:0,y:0},touchAim={x:0,y:0},mouseWorld=null,shoot=false,roll=false,aiming=false,rollQueued=false,shotQueued=false;
function tone(f=500,d=.06,type='square',volume=.025){if(!sound)return;try{audio ||=new AudioContext();void audio.resume();const o=audio.createOscillator(),gain=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(40,f*.35),audio.currentTime+d);gain.gain.setValueAtTime(volume,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(gain);gain.connect(audio.destination);o.start();o.stop(audio.currentTime+d);}catch{}}
const neutral=()=>({x:0,y:0,ax:1,ay:0,shoot:false,roll:false});
function resetInput(){keys.clear();move={x:0,y:0};touchAim={x:0,y:0};shoot=false;roll=false;rollQueued=false;shotQueued=false;aiming=false;mouseWorld=null;for(const el of document.querySelectorAll('.stick i'))el.style.transform='';session.send('input',neutral());}
function localPlayer(){return session.state.gameState?.players.find(p=>p.id===session.state.sessionId);}
function setPaused(value){paused=value;resetInput();$('#pause').textContent=paused?'▶ Resume':'Ⅱ Pause';renderUI();}
const portraitCache=new Map();function portrait(color){if(!portraitCache.has(color))portraitCache.set(color,sprite('player',color).toDataURL());return portraitCache.get(color);}
function renderUI(){const s=session.state,g=s.gameState,me=localPlayer(),connected=s.status==='connected';
 $('#connection').textContent=s.status==='idle'?'READY TO CONNECT':s.status.toUpperCase();$('.live-dot').classList.toggle('online',connected);$('#occupancy').textContent=`${s.players.length} / 4`;
 $('#room-code').textContent=s.code?`ROOM ${s.code} ⧉`:'PRIVATE ROOM';$('#room-code').disabled=!connected;$('#invite').disabled=!connected;$('#leave').disabled=!connected;
 $('#party').innerHTML=g?.players.length?g.players.map(p=>`<div class="crew-member"><img src="${portrait(p.color)}" alt=""><div><strong style="color:${p.color}">P${p.number} · ${p.name}${p.id===s.sessionId?' <em>YOU</em>':''}</strong><small>${g.phase==='lobby'?(p.ready?'READY':'CHOOSING WEAPON'):p.hp<=0?'DOWNED · NEEDS REVIVE':`${Math.ceil(p.hp)} HP · ${p.weapon.toUpperCase()}`}</small><div class="crew-health"><i style="width:${p.hp/p.maxHp*100}%;background:${p.color}"></i></div></div><span class="crew-status">${p.hp<=0?'✚':p.ready?'✓':'·'}</span></div>`).join(''):'<p class="empty-party">Create a room to start.<br>Solo adventurers welcome.</p>';
 $('#wave').textContent=g?String(g.wave).padStart(2,'0'):'—';$('#enemies').textContent=g?.enemies.length??'—';$('#health').textContent=me?`${Math.ceil(me.hp)} / ${me.maxHp}`:'— / 100';$('#health-fill').style.width=`${me?me.hp/me.maxHp*100:0}%`;$('#health-fill').style.background=me?.color||'#f3b966';$('#identity').textContent=me?`P${me.number} · ${me.name.toUpperCase()}`:'YOUR EXPLORER';$('#identity').style.color=me?.color||'';
 $('#dodge-label').textContent=me?.rollCooldown>0?`ROLL ${me.rollCooldown.toFixed(1)}s`:'ROLL READY';$('#dodge-fill').style.width=`${me?Math.max(0,1-me.rollCooldown/1.4)*100:100}%`;
 for(const b of document.querySelectorAll('[data-weapon]')){b.setAttribute('aria-pressed',String(b.dataset.weapon===(me?.weapon||'pistol')));b.disabled=connected&&g?.phase!=='lobby';}
 $('#upgrades').hidden=g?.phase!=='break';$('#break-timer').textContent=`NEXT WAVE IN ${Math.ceil(g?.breakIn||0)}s`;$('#upgrade-note').textContent=me?.credits>0?`${me.credits} reward choice${me.credits===1?'':'s'} available — every teammate earns their own.`:'Reward chosen. Get ready for the next wave.';for(const b of document.querySelectorAll('[data-upgrade]'))b.disabled=!me?.credits||g?.phase!=='break';
 $('#downed').hidden=!connected||!g||me?.hp>0||g.phase==='defeat';$('#downed').textContent=me?.revive>0?`REVIVING · ${Math.round(me.revive/2*100)}%`:'YOU ARE DOWN · Stand near a teammate to be revived';
 let title='',text='',kicker='THE VAULT IS WAITING',admission=false,ready=false,retry=false,restart=false,newRoom=false;
 if(gpuError){title='A graphics device is needed';text=gpuError;retry=true;}
 else if(s.status==='idle'||s.status==='offline'){title='Better together.';text='Create a private room, or follow your crew inside.';admission=true;}
 else if(!connected){title=s.status==='full'?'The crew is full':s.status==='error'?'That vault has closed':s.status==='reconnecting'?'Rejoining your crew…':'Opening the vault…';text=s.error||'Connecting to your private dungeon.';retry=s.status==='full';newRoom=s.status==='error';}
 else if(paused){title='Taking a breath.';text='Your controls are paused. The shared dungeon continues — your crew is still inside.';retry=true;kicker='LOCAL PAUSE';}
 else if(g?.phase==='lobby'){title=me?.ready?'Waiting for your crew…':'Pick a weapon. Ready up.';text=`Room ${s.code}. Invite friends, or start solo. Everyone in the lobby must be ready.`;ready=true;kicker='YOUR RUN STARTS HERE';}
 else if(g?.phase==='defeat'){title='The crew has fallen.';text=`Wave ${g.wave} reached. ${[...g.players].sort((a,b)=>a.number-b.number)[0]?.id===s.sessionId?'Gather your courage and try again.':'The crew leader can restart the run.'}`;restart=[...g.players].sort((a,b)=>a.number-b.number)[0]?.id===s.sessionId;kicker='ONE MORE RUN';}
 $('#overlay').hidden=!title;$('#overlay-title').textContent=title;$('#overlay-text').textContent=text;$('#overlay-kicker').textContent=kicker;$('#admission').hidden=!admission;$('#ready').hidden=!ready;$('#ready').textContent=me?.ready?'Cancel ready':'Ready up →';$('#retry').hidden=!retry;$('#retry').textContent=gpuError?'Reload game':paused?'Resume game':'Retry joining';$('#restart').hidden=!restart;$('#new-room').hidden=!newRoom;
 if(g){$('#event').textContent=g.event.text;if(previousPhase&&previousPhase!==g.phase)tone(g.phase==='break'?750:220,.2,'triangle');previousPhase=g.phase;const newShots=g.shots.filter(s=>s.owner===session.state.sessionId).length;if(newShots>previousShots)tone(me?.weapon==='scatter'?140:420,.045,'sawtooth',.018);previousShots=newShots;if(me?.hp<=0&&!dead)tone(100,.3,'sine');dead=me?.hp<=0;}
}
session.subscribe(renderUI);
function connect(options){paused=false;resetInput();session.options={...options};session.state.code=null;void session.connect();}
$('#create').onclick=()=>{const code=$('#join-code').value.trim().toUpperCase();if(code&&!/^[A-Z0-9]{4}$/.test(code)){$('#overlay-text').textContent='Enter a four-character code or leave it blank for a generated room.';return;}connect({create:true,...(code?{code}:{})});};$('#new-room').onclick=()=>connect({create:true});$('#join').onclick=()=>{const code=$('#join-code').value.trim().toUpperCase();if(!/^[A-Z0-9]{4}$/.test(code)){$('#overlay-text').textContent='Enter the four-character code from your crew.';return;}connect({code});};$('#join-code').addEventListener('keydown',e=>{if(e.key==='Enter')$('#join').click();});
$('#ready').onclick=()=>{session.send('ready');tone();};$('#restart').onclick=()=>{resetInput();session.send('restart');};$('#retry').onclick=()=>gpuError?location.reload():paused?setPaused(false):void session.connect();$('#leave').onclick=()=>{resetInput();session.disconnect();session.state.code=null;history.replaceState(null,'',location.pathname);renderUI();};
async function copyInvite(){if(!session.state.code)return;const url=new URL(location.href);url.searchParams.set('room',session.state.code);try{await navigator.clipboard.writeText(url.href);$('#invite-note').textContent='Invite copied. Your crew can join anytime.';}catch{$('#invite-note').textContent=`Share code ${session.state.code} with your crew.`;}}
$('#invite').onclick=copyInvite;$('#room-code').onclick=copyInvite;
for(const b of document.querySelectorAll('[data-weapon]'))b.onclick=()=>{session.send('weapon',b.dataset.weapon);tone();b.blur();};for(const b of document.querySelectorAll('[data-upgrade]'))b.onclick=()=>{session.send('upgrade',b.dataset.upgrade);tone(800,.12,'triangle');b.blur();};
$('#pause').onclick=()=>setPaused(!paused);$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'Sound on':'Sound off';$('#sound').setAttribute('aria-pressed',String(sound));tone(660,.1,'triangle');};$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#ui_layer').requestFullscreen();}catch{$('#event').textContent='Fullscreen is unavailable in this browser window.';}};
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if((k==='p'||k==='escape')&&!e.repeat){setPaused(!paused);return;}if(k===' '&&!e.repeat&&!paused)rollQueued=true;if(['1','2','3'].includes(k))session.send('weapon',WEAPONS[Number(k)-1].id);keys.add(k);});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',resetInput);document.addEventListener('visibilitychange',()=>{if(document.hidden)resetInput();});
const canvas=$('#game');const pointerAim=e=>{if(!renderer)return;const r=canvas.getBoundingClientRect();mouseWorld=renderer.screenToWorld((e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height);};
canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'||paused)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);shoot=true;shotQueued=true;pointerAim(e);});canvas.addEventListener('pointermove',pointerAim);canvas.addEventListener('pointerup',()=>shoot=false);canvas.addEventListener('pointercancel',resetInput);canvas.addEventListener('lostpointercapture',()=>shoot=false);canvas.addEventListener('contextmenu',e=>e.preventDefault());
function stickControl(el,aim=false){let pointer=null;function update(e){const r=el.getBoundingClientRect();const v=normalized((e.clientX-r.left-r.width/2)/30,(e.clientY-r.top-r.height/2)/30);el.querySelector('i').style.transform=`translate(${v.x*23}px,${v.y*23}px)`;if(aim){touchAim=v;aiming=Math.hypot(v.x,v.y)>.15;}else move=v;}
 el.addEventListener('pointerdown',e=>{if(pointer!==null)return;e.preventDefault();pointer=e.pointerId;el.setPointerCapture(pointer);update(e);});el.addEventListener('pointermove',e=>{if(pointer===e.pointerId)update(e);});const release=e=>{if(pointer!==e.pointerId)return;pointer=null;el.querySelector('i').style.transform='';if(aim){touchAim={x:0,y:0};aiming=false;}else move={x:0,y:0};session.send('input',neutral());};for(const event of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(event,release);
}
stickControl($('#move-stick'));stickControl($('#aim-stick'),true);$('#touch-roll').addEventListener('pointerdown',e=>{e.preventDefault();roll=true;rollQueued=true;e.currentTarget.setPointerCapture(e.pointerId);});for(const event of ['pointerup','pointercancel','lostpointercapture'])$('#touch-roll').addEventListener(event,()=>roll=false);
const inputTimer=setInterval(()=>{if(disposed)return;const me=localPlayer();let aim={x:Math.cos(me?.angle||0),y:Math.sin(me?.angle||0)};if(aiming)aim=touchAim;else if(mouseWorld&&me)aim=normalized(mouseWorld.x-me.x,mouseWorld.y-me.y);session.send('input',makeInput(keys,move,aim,shoot||aiming||shotQueued,roll||keys.has(' ')||rollQueued,paused||!!gpuError));rollQueued=false;shotQueued=false;},50);
try{renderer=await createRenderer(canvas,e=>{gpuError=e.message;resetInput();renderUI();});}catch(e){gpuError=e.message;renderUI();}
function frame(now){if(disposed)return;renderer?.draw(session.state.gameState,session.state.sessionId,now);raf=requestAnimationFrame(frame);}raf=requestAnimationFrame(frame);
const inviteCode=new URL(location.href).searchParams.get('room');if(inviteCode)connect({code:inviteCode.toUpperCase()});
// Read-only state inspection supports reproducible local and public browser verification.
window.__gungeon={state:()=>session.state,ready:()=>!!renderer&&!gpuError};
window.addEventListener('pagehide',()=>{disposed=true;resetInput();clearInterval(inputTimer);cancelAnimationFrame(raf);session.disconnect();renderer?.dispose();},{once:true});
